1977474741 patch 1
justjavac/awesome-wechat-weapp pull request #312
Opened 2021-06-07 11:25 UTC by 1977474741

添加vue-custom-hooks、image-cropper

2021-06-08 00:19 UTC, justjavac requested changes

2021-06-08 00:19 UTC, justjavac commented on README.md
> +- [vue-custom-hooks ★100+](https://github.com/1977474741/vue-custom-hooks) - 💯基于vue的自定义钩子（多任务通知解决方案），支持h5、uni-app、wepy、mpvue
这个好像不太符合，推荐你提交到 awesome-vue 类似的仓库里面

2021-06-08 06:42 UTC, 1977474741 commented on README.md
> +- [vue-custom-hooks ★100+](https://github.com/1977474741/vue-custom-hooks) - 💯基于vue的自定义钩子（多任务通知解决方案），支持h5、uni-app、wepy、mpvue
可能名字误导了，这个应用场景主要是在小程序环境下，只是基于vue而已，小程序第三方框架都支持vue的，而且第一版其实只支持小程序的，只是后面兼容了h5，还是以小程序为主。

2021-06-08 09:15 UTC, justjavac commented on README.md
> +- [vue-custom-hooks ★100+](https://github.com/1977474741/vue-custom-hooks) - 💯基于vue的自定义钩子（多任务通知解决方案），支持h5、uni-app、wepy、mpvue
还是去掉吧

2021-06-09 02:24 UTC, 1977474741 commented on README.md
> +- [vue-custom-hooks ★100+](https://github.com/1977474741/vue-custom-hooks) - 💯基于vue的自定义钩子（多任务通知解决方案），支持h5、uni-app、wepy、mpvue
好吧，可惜了这么好的插件。已经把vue-custom-hooks拿掉了

2021-06-09 04:09 UTC, justjavac approved these changes

2021-06-09 04:10 UTC, merged